"""
Config Translate Agent — Sprint 14.

Takes a ParseResult from cisco_config_parser, enriches each section with
RAG database lookups, then calls Claude to produce the ExtremeXOS equivalent.

Returns a TranslationResult containing:
  - translated sections (one per input section)
  - verification badges per command line
  - overall stats
  - raw EXOS script (ready to download)
"""

from __future__ import annotations

import logging
import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import anthropic

from src.config import ANTHROPIC_API_KEY, CLAUDE_MODEL
from src.parsers.cisco_config_parser import ConfigSection, ParseResult

logger = logging.getLogger(__name__)

# ── Constants ────────────────────────────────────────────────────────────────

_PROMPT_PATH = Path(__file__).parent / "prompts" / "system_config_translator.md"
_MAX_TOKENS_PER_CALL = 4096
_CHUNK_SIZE = 12          # max sections per Claude call for large configs
_RAG_TOP_K = 3            # RAG results to fetch per section

# Target OS options — only EXOS active in Sprint 14
TARGET_OS_OPTIONS: dict[str, dict] = {
    "extreme_exos": {
        "label":   "ExtremeXOS / Switch Engine 33.x",
        "col":     "extreme_exos",
        "version": "ExtremeXOS 33.x",
        "active":  True,
    },
    "extreme_voss": {
        "label":   "VOSS / Fabric Engine 9.x",
        "col":     "extreme_voss",
        "version": "VOSS 9.x",
        "active":  False,   # Sprint 15
    },
    "extreme_slxos": {
        "label":   "SLX-OS 20.x",
        "col":     "extreme_slxos",
        "version": "SLX-OS 20.x",
        "active":  False,   # Future
    },
}

SOURCE_OS_OPTIONS: dict[str, dict] = {
    "cisco_ios": {
        "label":  "Cisco IOS",
        "col":    "cisco_ios",
        "active": True,
    },
    "cisco_iosxe": {
        "label":  "Cisco IOS-XE 17.x",
        "col":    "cisco_iosxe",
        "active": True,
    },
    "cisco_nxos": {
        "label":  "Cisco NX-OS 10.x",
        "col":    "cisco_nxos",
        "active": True,
    },
    "extreme_exos": {
        "label":  "ExtremeXOS / Switch Engine 33.x",
        "col":    "extreme_exos",
        "active": False,   # Sprint 16
    },
    "extreme_voss": {
        "label":  "VOSS / Fabric Engine 9.x",
        "col":    "extreme_voss",
        "active": False,   # Sprint 16
    },
}


# ── Data classes ─────────────────────────────────────────────────────────────

@dataclass
class TranslatedLine:
    """One line of translated EXOS output with its verification status."""
    text: str
    status: str    # "verified" | "unverified" | "caveat" | "no_equivalent" | "comment"
    rag_match: bool = False


@dataclass
class TranslatedSection:
    """Translation of one ConfigSection."""
    original: ConfigSection
    translated_lines: list[TranslatedLine] = field(default_factory=list)
    rag_hits: int = 0
    has_caveats: bool = False
    has_no_equivalent: bool = False
    raw_output: str = ""

    @property
    def exos_text(self) -> str:
        return "\n".join(l.text for l in self.translated_lines if l.text.strip())


@dataclass
class TranslationResult:
    """Full result returned by translate_config()."""
    sections: list[TranslatedSection]
    source_os: str
    target_os: str
    target_version: str
    stats: dict
    warnings: list[str] = field(default_factory=list)

    @property
    def full_script(self) -> str:
        """Concatenated EXOS script ready for download."""
        header = (
            f"# ════════════════════════════════════════════════════\n"
            f"# CISCO → {self.target_version} Translation\n"
            f"# Generated by CISCO-EN CLI Mapping Agent\n"
            f"# Source OS: {self.source_os}\n"
            f"# ════════════════════════════════════════════════════\n\n"
        )
        body = "\n\n".join(s.exos_text for s in self.sections if s.exos_text.strip())
        return header + body

    @property
    def total_rag_hits(self) -> int:
        return sum(s.rag_hits for s in self.sections)

    @property
    def caveat_count(self) -> int:
        return sum(1 for s in self.sections if s.has_caveats)

    @property
    def no_equivalent_count(self) -> int:
        return sum(1 for s in self.sections if s.has_no_equivalent)


# ── RAG helper ───────────────────────────────────────────────────────────────

def _rag_lookup(section: ConfigSection, target_col: str) -> list[dict]:
    """
    Search the RAG database for commands matching this section.
    Returns up to _RAG_TOP_K results as dicts with 'functional_intent' and target col value.
    """
    try:
        from src.rag.search import search
        # Build a query from the section header + key sub-commands
        query_parts = [section.header]
        for cl in section.body[:5]:   # limit to first 5 sub-commands
            query_parts.append(cl.text)
        query = " ".join(query_parts)

        results = search(
            query=query,
            top_k=_RAG_TOP_K,
            threshold=0.30,
            search_mode="Hybrid",
        )
        # Filter to rows that have a value in the target column
        hits = [r for r in results if r.get(target_col)]
        return hits[:_RAG_TOP_K]
    except Exception as e:
        logger.warning(f"RAG lookup failed for section '{section.header}': {e}")
        return []


def _format_rag_context(hits: list[dict], target_col: str, target_version: str) -> str:
    """Format RAG hits as context text for the Claude prompt."""
    if not hits:
        return ""
    lines = [f"\n### RAG Reference ({target_version}) — verified syntax:\n"]
    for h in hits:
        intent = h.get("functional_intent", "")
        exos_cmd = h.get(target_col, "")
        if intent and exos_cmd:
            lines.append(f"- Intent: {intent}")
            lines.append(f"  {target_version}: {exos_cmd}")
    return "\n".join(lines)


# ── System prompt loader ──────────────────────────────────────────────────────

_system_prompt_cache: Optional[str] = None

def _get_system_prompt() -> str:
    global _system_prompt_cache
    if _system_prompt_cache is None:
        _system_prompt_cache = _PROMPT_PATH.read_text()
    return _system_prompt_cache


# ── Translation core ──────────────────────────────────────────────────────────

def _build_section_prompt(
    section: ConfigSection,
    rag_hits: list[dict],
    target_col: str,
    target_version: str,
    source_os: str,
) -> str:
    """Build the user-turn prompt for a single section translation."""
    rag_ctx = _format_rag_context(rag_hits, target_col, target_version)

    prompt = (
        f"Translate the following Cisco {source_os.upper()} configuration section "
        f"to {target_version}.\n\n"
        f"### Input (Cisco {source_os.upper()}):\n"
        f"```\n{section.raw_text}\n```\n"
    )
    if rag_ctx:
        prompt += rag_ctx
    prompt += (
        f"\n\nProduce only the {target_version} equivalent. "
        f"Follow all rules in the system prompt exactly. "
        f"Do not explain — output only the translated config block."
    )
    return prompt


def _build_chunk_prompt(
    sections: list[ConfigSection],
    rag_map: dict[str, list[dict]],
    target_col: str,
    target_version: str,
    source_os: str,
    chunk_index: int,
    total_chunks: int,
) -> str:
    """Build prompt for a chunk of sections (used for large configs)."""
    prompt_parts = [
        f"Translate the following Cisco {source_os.upper()} configuration sections "
        f"to {target_version}. "
        f"[Chunk {chunk_index + 1} of {total_chunks}]\n\n"
    ]
    for sec in sections:
        hits = rag_map.get(sec.header, [])
        rag_ctx = _format_rag_context(hits, target_col, target_version)
        prompt_parts.append(
            f"### Section: {sec.section_type.upper()} — {sec.header}\n"
            f"```\n{sec.raw_text}\n```"
        )
        if rag_ctx:
            prompt_parts.append(rag_ctx)
        prompt_parts.append("")

    prompt_parts.append(
        f"Translate each section separately. "
        f"Follow all rules in the system prompt exactly."
    )
    return "\n".join(prompt_parts)


def _parse_translated_output(raw: str) -> list[TranslatedLine]:
    """Parse Claude's raw output into TranslatedLine objects with status badges."""
    lines = []
    for line in raw.splitlines():
        stripped = line.strip()
        if not stripped:
            lines.append(TranslatedLine(text="", status="comment"))
            continue

        if stripped.startswith("# NO EQUIVALENT"):
            status = "no_equivalent"
        elif stripped.startswith("# CAVEAT"):
            status = "caveat"
        elif stripped.startswith("# Unverified"):
            status = "unverified"
        elif stripped.startswith("# Verified"):
            status = "verified"
        elif stripped.startswith("# NX-OS PREREQUISITE"):
            status = "comment"
        elif stripped.startswith("#"):
            status = "comment"
        else:
            # Actual EXOS command — default to unverified until confirmed
            status = "unverified"

        lines.append(TranslatedLine(
            text=line,
            status=status,
            rag_match=False,
        ))
    return lines


def _call_claude(user_prompt: str) -> tuple[str, float]:
    """Call Claude API and return (text response, elapsed_seconds)."""
    t0 = time.perf_counter()
    client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    message = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=_MAX_TOKENS_PER_CALL,
        system=_get_system_prompt(),
        messages=[{"role": "user", "content": user_prompt}],
    )
    elapsed = round(time.perf_counter() - t0, 2)
    return (message.content[0].text if message.content else ""), elapsed


# ── Public API ────────────────────────────────────────────────────────────────

def translate_config(
    parse_result: ParseResult,
    target_os_key: str = "extreme_exos",
    progress_callback=None,   # optional callable(step: int, total: int, msg: str)
) -> TranslationResult:
    """
    Translate a parsed Cisco config to the target OS.

    Args:
        parse_result:      Output from cisco_config_parser.parse_config()
        target_os_key:     Key from TARGET_OS_OPTIONS (default: "extreme_exos")
        progress_callback: Optional function for UI progress updates

    Returns:
        TranslationResult with translated sections and stats
    """
    target = TARGET_OS_OPTIONS.get(target_os_key, TARGET_OS_OPTIONS["extreme_exos"])
    target_col = target["col"]
    target_version = target["version"]
    source_os = parse_result.source_os if parse_result.source_os != "unknown" else "IOS"

    # Filter to translatable sections only
    translatable = [
        s for s in parse_result.sections
        if s.section_type not in ("comment", "prose")
    ]

    total = len(translatable)
    translated_sections: list[TranslatedSection] = []
    warnings: list[str] = []

    def _progress(step: int, msg: str):
        if progress_callback:
            progress_callback(step, total, msg)

    # ── RAG lookup for all sections (in batch for efficiency) ──────────────
    rag_map: dict[str, list[dict]] = {}
    t_rag_start = time.perf_counter()
    for i, sec in enumerate(translatable):
        _progress(i, f"Looking up RAG database: {sec.header[:50]}…")
        hits = _rag_lookup(sec, target_col)
        rag_map[sec.header] = hits
    t_rag_total = round(time.perf_counter() - t_rag_start, 2)

    # ── Decide: section-by-section or chunked ─────────────────────────────
    use_chunks = total > _CHUNK_SIZE
    claude_call_times: list[float] = []

    if use_chunks:
        # Split into chunks of _CHUNK_SIZE sections
        chunks = [
            translatable[i:i + _CHUNK_SIZE]
            for i in range(0, total, _CHUNK_SIZE)
        ]
        total_chunks = len(chunks)
        raw_outputs: list[str] = []

        for ci, chunk in enumerate(chunks):
            _progress(
                len(raw_outputs) * _CHUNK_SIZE,
                f"Translating chunk {ci + 1}/{total_chunks}…"
            )
            prompt = _build_chunk_prompt(
                chunk, rag_map, target_col, target_version,
                source_os, ci, total_chunks,
            )
            try:
                raw, elapsed = _call_claude(prompt)
                claude_call_times.append(elapsed)
                raw_outputs.append(raw)
            except Exception as e:
                logger.error(f"Claude call failed for chunk {ci}: {e}")
                warnings.append(f"Chunk {ci + 1} translation failed: {e}")
                raw_outputs.append(f"# ERROR: Translation failed for chunk {ci + 1}\n# {e}")

        # Re-split chunked output back into per-section TranslatedSections
        # (best-effort: split on section header comments)
        full_raw = "\n\n".join(raw_outputs)
        for sec in translatable:
            hits = rag_map.get(sec.header, [])
            ts = TranslatedSection(
                original=sec,
                rag_hits=len(hits),
                raw_output=full_raw,  # full raw for chunk mode
            )
            ts.translated_lines = _parse_translated_output(
                _extract_section_from_chunk(full_raw, sec.header, target_version)
            )
            ts.has_caveats = any(l.status == "caveat" for l in ts.translated_lines)
            ts.has_no_equivalent = any(l.status == "no_equivalent" for l in ts.translated_lines)
            translated_sections.append(ts)

    else:
        # Section-by-section (preferred for configs up to ~_CHUNK_SIZE sections)
        for i, sec in enumerate(translatable):
            _progress(i, f"Translating: {sec.header[:50]}…")
            hits = rag_map.get(sec.header, [])

            prompt = _build_section_prompt(
                sec, hits, target_col, target_version, source_os
            )
            try:
                raw, elapsed = _call_claude(prompt)
                claude_call_times.append(elapsed)
            except Exception as e:
                logger.error(f"Claude call failed for section '{sec.header}': {e}")
                warnings.append(f"Section '{sec.header}' failed: {e}")
                raw = f"# ERROR: Translation failed\n# {e}"

            tlines = _parse_translated_output(raw)

            # Mark lines as rag_match=True if they appear in RAG hits
            exos_cmds_in_rag = {h.get(target_col, "").strip() for h in hits if h.get(target_col)}
            for tl in tlines:
                if tl.text.strip() in exos_cmds_in_rag:
                    tl.rag_match = True
                    tl.status = "verified"

            ts = TranslatedSection(
                original=sec,
                translated_lines=tlines,
                rag_hits=len(hits),
                raw_output=raw,
            )
            ts.has_caveats = any(l.status == "caveat" for l in tlines)
            ts.has_no_equivalent = any(l.status == "no_equivalent" for l in tlines)
            translated_sections.append(ts)

    # ── Stats ──────────────────────────────────────────────────────────────
    all_lines = [l for ts in translated_sections for l in ts.translated_lines]
    t_claude_total = round(sum(claude_call_times), 2)
    stats = {
        "sections_translated": len(translated_sections),
        "rag_hits_total": sum(ts.rag_hits for ts in translated_sections),
        "lines_verified": sum(1 for l in all_lines if l.status == "verified"),
        "lines_unverified": sum(1 for l in all_lines if l.status == "unverified"),
        "caveats": sum(1 for l in all_lines if l.status == "caveat"),
        # ── Timing breakdown ──
        "time_rag_s": t_rag_total,
        "time_claude_s": t_claude_total,
        "time_claude_calls": len(claude_call_times),
        "time_claude_per_call_s": [round(t, 2) for t in claude_call_times],
        "no_equivalents": sum(1 for l in all_lines if l.status == "no_equivalent"),
        "warnings": len(warnings),
        "chunked": use_chunks,
    }

    return TranslationResult(
        sections=translated_sections,
        source_os=source_os,
        target_os=target_os_key,
        target_version=target_version,
        stats=stats,
        warnings=warnings,
    )


def _extract_section_from_chunk(full_raw: str, section_header: str, target_version: str) -> str:
    """
    Best-effort: extract the translated block for a specific section
    from a chunked Claude response.
    """
    # Look for the section marker comment Claude was instructed to emit
    short = section_header[:40].replace("interface ", "").replace("router ", "")
    pattern = re.compile(
        rf"#\s*──+\s*{re.escape(short[:20])}.*?(?=#\s*──|$)",
        re.IGNORECASE | re.DOTALL,
    )
    m = pattern.search(full_raw)
    if m:
        return m.group(0).strip()
    # Fallback: return the full raw output for this section
    return f"# Source: {section_header}\n{full_raw}"
